version: '3'

volumes:
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: 282428440465.dkr.ecr.us-east-1.amazonaws.com/overflowedminds_production_django
    depends_on:
      - redis
      - frontend
    env_file:
      - backend/.envs/.production/.django
      - backend/.envs/.production/.postgres
    command: /start

  frontend:
    build:
      context: .
      dockerfile: compose/production/frontend/Dockerfile
    image: 282428440465.dkr.ecr.us-east-1.amazonaws.com/overflowedminds_production_frontend
    env_file:
      - frontend/.envs/.production/.react

  traefik:
    build:
      context: .
      dockerfile: compose/production/traefik/Dockerfile
    image: 282428440465.dkr.ecr.us-east-1.amazonaws.com/overflowedminds_production_traefik
    restart: always
    depends_on:
      - django
    volumes:
      # this is necessary so the certificate generated in the container persists on container restarts
      # and traefik does not request new certificates for every restart (as long as the volume exists)
      - production_traefik:/etc/traefik/acme:z
      # Required for Traefik to listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # https://github.com/traefik/traefik/issues/4352#issuecomment-452285978
    # https://community.traefik.io/t/traefik-and-pihole-with-docker-forward-client-ip/9933/3?u=newlog
    # unfortunately, we need to expose all the host network stack to this container so docker does not
    # do handle networking itself for the container and traefik can get the client's IP
    # https://docs.docker.com/network/host/
    network_mode: host
    #ports:
    #  - 80:80
    #  - 443:443
    env_file:
      - backend/.envs/.production/.traefik
    command: /start

  redis:
    image: redis:5.0
  
  awscli:
    build:
      context: .
      dockerfile: compose/production/aws/Dockerfile
    env_file:
      - backend/.envs/.production/.django
