# Generated by Django 3.0.11 on 2020-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
