# Generated by Django 3.0.11 on 2021-07-18 14:16

from django.db import migrations, models
import django_extensions.db.fields

from overflowedminds_backend.writings.models import Writing


def migrate_data_forward(apps, schema_editor):
    for instance in Writing.objects.all():
        print(f"\nGenerating slug for {instance}")
        instance.save()  # Will trigger slug update


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0005_writing_internal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='writing',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='writing',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=60, null=True, populate_from='title', unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
    ]
