# Generated by Django 3.0.11 on 2021-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0003_auto_20210718_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
