# Generated by Django 3.0.11 on 2021-07-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20201213_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
