# Generated by Django 3.0.11 on 2021-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0004_auto_20210725_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
