# Generated by Django 3.0.11 on 2021-09-24 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0005_writing_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedUser',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='writing',
            name='likes',
        ),
        migrations.AddConstraint(
            model_name='anonymizeduser',
            constraint=models.UniqueConstraint(fields=('id', 'identity'), name='Non repeated entries'),
        ),
        migrations.AddField(
            model_name='writing',
            name='likes',
            field=models.ManyToManyField(to='writings.AnonymizedUser'),
        ),
    ]
