name: Overflowedminds Deployment

on:
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: echo "${PWD}"
      - run: ls -la "${PWD}"
      - run: ls -la "${PWD}/deployment"
      - run: ls -la "${PWD}/deployment/ansible"
      - run: ls -la "${PWD}/*/*"

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: "${PWD}/deployment/ansible/deploy.yml"
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            overflowedminds.net

            [group1]
            overflowedminds.net
          options: |
            --limit group1
            --verbose

