name: Overflowedminds Deployment

on:
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: echo "${PWD}"

      - name: 'deployment pending'
        uses: 'newlog/deployment-status-update@0.2.0'
        with:
          state: 'pending'
          token: '${{ github.token }}'

      - name: 'deployment success'
        if: success()
        uses: 'newlog/deployment-status-update@0.2.0'
        with:
          status: 'success'
          run_id: '${{ github.run_id }}'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'newlog/deployment-status-update@0.2.0'
        with:
          state: 'failure'
          run_id: '${{ github.run_id }}'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
