name: Overflowedminds Deployment

on:
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: echo "${PWD}"

      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'pending'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment success'
        #if: success()
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment failure'
        #if: failure()
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}'
